// interface between the lexer and the main program
#ifndef FLEX_INTERFACE_HEADER
#define FLEX_INTERFACE_HEADER

enum InputToken
{
	Eof,
	Eol,
	Semicolon,
	Argument,
	ErrTokenTooLong,
	ErrMultipleSemicolons,
};
#define InputToken enum InputToken

#define MAX_TOKEN_LENGTH 1024

// lexer function generated by flex
#define YY_DECL InputToken yylex (void)
YY_DECL;

void set_input(int argc, char **argv);

#endif
